### ISSUE TITLE
 2022年4月7日 数据丢失

### ISSUE THREAD

**Issue by sinchang** [TienZhao/covid-shanghai#11]
2022年4月7日 的 text 文件规则跟之前的不一致导致数据丢失

**Comment by TienZhao** [comment]
感谢提醒！我的锅哈哈哈~
出错原因是忘记运行text.py了，已经在Commit https://github.com/TienZhao/covid-shanghai/commit/e3cb227795098bcf7986eeb5a9b481a2709609d5 这里修复。
最近情绪压力比较大，维护的时候可能也会有些小问题，请您见谅~

**Comment by sinchang** [comment]
@TienZhao 没事，注意休息。

**Comment by sinchang** [comment]
@TienZhao  

不好意思，这些数据好像因为没有分隔符 `，` 导致没有生成到 json 文件。

<img width="222" alt="image" src="https://user-images.githubusercontent.com/3297859/162381444-c5364eed-b280-4c38-afe2-3df338d21472.png">

**Comment by TienZhao** [comment]
是的，之前没有留意到这几个区地址后面又不加标点了，前几天的已经回算修正，之后注意哈哈~
