### ISSUE TITLE
请问哪里有每日治愈人数的汇总吗？

### ISSUE THREAD

**Issue by BarryBA** [TienZhao/covid-shanghai#14]
请问哪里有每日治愈人数的汇总吗？包括病好了离开方舱/医院等的人数

**Comment by TienZhao** [comment]
目前我也不知道这方面的平台，但我觉得这也是一个很有意义的数字。如果你愿意来做一个统计的话，可以直接改在analysis.xlsx里提交pull request喔~

**Comment by TienZhao** [comment]
上海市卫健委在2022年4月10日之前不公布每日的无症状感染者出舱人数，仅仅公布确诊患者治愈人数，因此目前可能没有公开渠道获得这方面的数据。
