### ISSUE TITLE
[性能优化提升95%]将地址转坐标提前在服务器进行

### ISSUE THREAD

**Issue by huobaolajiao** [TienZhao/covid-shanghai#3]
为什么会将地图服务器打崩掉呢？因为将文字地址转坐标将重复在每个用户手机电脑上执行，造成大量api查询。
然而这些坐标每日更新最多两次，相对静止，因此可以在服务器上将地址和坐标打包为json，
如： {"name":"浦东新区xx路","lon":120,"lat":31}，再在本地渲染坐标logo，即快速，又省流量和api调用量。

**Comment by TienZhao** [comment]
英雄所见略同。有办法就一起来pull request吧！
截止3月16日下午的地址坐标数据：
https://github.com/TienZhao/covid-shanghai/blob/main/positions.json
坐标来自amap，可以配合[shanghai.html](https://github.com/TienZhao/covid-shanghai/blob/main/shanghai.html)使用。
下午的时候尝试了点击按钮->获取JSON->标点，但是从github.io加载文件太慢，体验不佳。
TODOs:

- [x] - 页面加载时就获取json，看看等待时间会不会缩短
- [ ] - 增加方法，用json数据标注地理位置时候，图标依然能够逐个/分批出现
- [x] - 增加预先转坐标生产json的方法，放在单独的文件里，使用单独的密钥运行。

---
按照当前的访问量和地址数量，远远没有达到百度昨天联系我时，声称收到的请求数。
但是由于今天没有联系上百度方面，也不能登录后台，所以尚不清楚具体出错的原因。
非常感谢你的建议！

**Comment by TienZhao** [comment]
更新在Commit https://github.com/TienZhao/covid-shanghai/commit/6608c5718dcd1bc3a47aeafdbf95e2aa41701777 里面了

**Comment by TienZhao** [comment]
数据点分批展示的需求，之前因为数量暴增，导致不再符合用户需求，用户只想快点看到结果，因此优先级降低。
但是，由于数据过多，造成新的异常情况被重新提出，之后会更新到 [issue](https://github.com/TienZhao/covid-shanghai/issues/7) 。
