### ISSUE TITLE
你这个好像不太全，可以看看我的

### ISSUE THREAD

**Issue by chenzhitong** [TienZhao/covid-shanghai#4]
你这个好像不太全，可以看看我的，手机高德扫码可查看详情。
不过我不打算一直维护了，因为现在已经有好多隔离14天的小区陆续开始解封了，应该将他们从地图上移除。但上海发布不会公布。这样下去标注的地点只会越来越多。

![9a124368abc87d068a3bebdfef7ea22](https://user-images.githubusercontent.com/6295602/158772953-44473753-1e1c-417b-991d-03621b244ec8.jpg)

**Comment by chenzhitong** [comment]
这是截止到3月16日22点的数据，数据来自上海发布

**Comment by TienZhao** [comment]
- 感谢关注，也非常高兴看到大家都在尽自己的努力，为疫情防控做出贡献。高德的DIY地图是个有趣的功能，学习了！
- 从3月6日至3月17日，这个项目总共标记了677个地址，来自上海市卫健委的确诊和无症状感染者住址。不代表小区封控情况。考虑到数据清洗去重方法的差别，我相信数据的完整度还是差不多的。
- 如果您能告诉我具体遗漏了哪些点，帮助这个项目进步，我将不胜感激！

**Comment by chenzhitong** [comment]
`来自上海市卫健委的确诊和无症状感染者住址` 
可能遗漏了**活动轨迹**，上海发布里有的会提到

**Comment by chenzhitong** [comment]
<img width="647" alt="e67a67f21ebc1597781cc06d68001a2" src="https://user-images.githubusercontent.com/6295602/158802790-99d6324f-d35b-4b75-bddc-f03bb58238c9.png">
这是你标注的

![ae539170dcfe983aa933780549f7318](https://user-images.githubusercontent.com/6295602/158802832-fc97df9c-3cc6-4c5f-a20e-befffaad6d2d.jpg)
这是我标注的

你可能缺了2月28日~3月5日的数据

**Comment by TienZhao** [comment]
感谢指点！


------------------ 原始邮件 ------------------
发件人: 陈志同 ***@***.***&gt;
发送时间: 2022年3月17日 19:53
收件人: TienZhao/covid-shanghai ***@***.***&gt;
抄送: TienZhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [TienZhao/covid-shanghai] 你这个好像不太全，可以看看我的 (Issue #4)





 

 这是你标注的 

 这是我标注的
 
你可能缺了2月28日~3月5日的数据
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zliu** [comment]
> 你这个好像不太全，可以看看我的，手机高德扫码可查看详情。 不过我不打算一直维护了，因为现在已经有好多隔离14天的小区陆续开始解封了，应该将他们从地图上移除。但上海发布不会公布。这样下去标注的地点只会越来越多。
> 
> ![9a124368abc87d068a3bebdfef7ea22](https://user-images.githubusercontent.com/6295602/158772953-44473753-1e1c-417b-991d-03621b244ec8.jpg)

解封的虽然不通知，是不是可以考虑给每个数据点加上发布日期，然后14天后如果没有新病例就自动删除该点。如果14天内有后续新的确诊/密接/无症状转确诊 之类的，就刷新数据点的发布日期？

**Comment by TienZhao** [comment]
是的，目前的数据范围就是最近14天。
显示日期是个很好的想法！我之后找机会，尽量尝试在符合监管要求的情况下更新，感谢您的建议！


------------------ 原始邮件 ------------------
发件人: Zhuo Liu ***@***.***&gt;
发送时间: 2022年3月20日 10:56
收件人: TienZhao/covid-shanghai ***@***.***&gt;
抄送: TienZhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[TienZhao/covid-shanghai] 你这个好像不太全，可以看看我的 (Issue #4)





  
你这个好像不太全，可以看看我的，手机高德扫码可查看详情。 不过我不打算一直维护了，因为现在已经有好多隔离14天的小区陆续开始解封了，应该将他们从地图上移除。但上海发布不会公布。这样下去标注的地点只会越来越多。
 

  
解封的虽然不通知，是不是可以考虑给每个数据点加上发布日期，然后14天后如果没有新病例就自动删除该点。如果14天内有后续新的确诊/密接/无症状转确诊 之类的，就刷新数据点的发布日期？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
