### ISSUE TITLE
这里只显示了每天增加的数据，但是缺少每天解封的数据

### ISSUE THREAD

**Issue by Erickrus** [TienZhao/covid-shanghai#5]
这里只显示了每天增加的数据，但是缺少每天解封的数据
可能这个数据不容易获得，如果可以获得 应该按照当前的快照来显示当前的情况。
每天累计略显不合理

另外，是不是可以按天显示数据，或者像高德地图——疫情地图，显示 21天内/14天内/7天内/昨天

**Comment by TienZhao** [comment]
您好，感谢对这个项目的关注。
首先，我要再次强调，如同页面中说明所示的，这个项目展示的数据是近14天的新增病例情况，和封锁以及解封情况无关。
其次，这个项目的数据来源于官方发布消息。受制于技术架构及政策法规原因，暂不接受其他非官方的数据来源。如果您有可信的封锁及解封数据来源，我很乐意了解。
最后我很赞成，您提出的基于不同时间维度展示数据的建议。实现这个想法，目前有这些困难。其一上海的官方平台并未发布3月6日之前的病历数据，也就是21天是无法获得的。其二这个项目目前由我一人维护，但是考虑到社区封控对生活的影响，接下来几天将没有时间开发新的功能。如果您非常希望实现的话，可以自己提交pull request。


------------------ 原始邮件 ------------------
发件人: Erickrus ***@***.***&gt;
发送时间: 2022年3月23日 10:28
收件人: TienZhao/covid-shanghai ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TienZhao/covid-shanghai] 这里只显示了每天增加的数据，但是缺少每天解封的数据 (Issue #5)





 
这里只显示了每天增加的数据，但是缺少每天解封的数据
 可能这个数据不容易获得，如果可以获得 应该按照当前的快照来显示当前的情况。
 每天累计略显不合理
 
另外，是不是可以按天显示数据，或者像高德地图——疫情地图，显示 21天内/14天内/7天内/昨天

**Comment by Erickrus** [comment]
https://github.com/Erickrus/covid-shanghai/commit/ef491a84e930cb563b6783b91d94dec88306d6d4

**Comment by TienZhao** [comment]
用透明度展示日期，好棒的主意！
感谢您通过邮件向我贡献的代码，刚才在 https://github.com/TienZhao/covid-shanghai/commit/39f669ea0a5c318b7da926f1f0ae350e64c610ac Commit中，将它更新到了shanghai.html页面上。
我也在支持者名单里向您致意。
