### ISSUE TITLE
有办法可以选择隐藏具体地址, 只显示图标吗?

### ISSUE THREAD

**Issue by blog2i2j** [TienZhao/covid-shanghai#8]
放大图的是地址全部显示反而看不清楚密集程度了.

**Comment by TienZhao** [comment]
可以点击上方地址按钮


------------------ 原始邮件 ------------------
发件人: blog2i2j ***@***.***&gt;
发送时间: 2022年3月31日 09:40
收件人: TienZhao/covid-shanghai ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TienZhao/covid-shanghai] 有办法可以选择隐藏具体地址, 只显示图标吗? (Issue #8)





 
放大图的是地址全部显示反而看不清楚密集程度了.
