### ISSUE TITLE
数据量太大了，地图显示不出来

### ISSUE THREAD

**Issue by umgsai** [TienZhao/covid-shanghai#9]

**Comment by umgsai** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/13217667/160960886-250ed833-2309-4d82-a2c2-3acef86a7007.png">

**Comment by TienZhao** [comment]
似乎和issue#6是一样的问题

------------------ 原始邮件 ------------------
发件人: 商商 ***@***.***&gt;
发送时间: 2022年3月31日 09:57
收件人: TienZhao/covid-shanghai ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TienZhao/covid-shanghai] 数据量太大了，地图显示不出来 (Issue #9)

**Comment by sinchang** [comment]
@TienZhao 可以考虑使用海量点标记 https://lbs.amap.com/demo/jsapi-v2/example/mass-markers/labelmarker-text

这是我的测试例子： https://covid-shanghai-map.vercel.app/

BTW： 网站使用到你的数据（通过访问 json 地址），如果有违法相关的协议，麻烦告知。

**Comment by TienZhao** [comment]
感谢您对项目的关注。
这个issue讨论的是网络安全防护异常触发导致的地图销毁问题。
我把您的建议和对您的回复放在了一个新的issue #10 里面。另外我也希望了解一下您的设备上现在的加载时间，谢谢。
